# Generated by Django 6.0.5 on 2026-05-17 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cor", models.CharField(default="#6366f1", max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name="tarefamodel",
            name="data_atualizacao",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tarefamodel",
            name="ordem",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tarefamodel",
            name="prazo",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tarefamodel",
            name="prioridade",
            field=models.CharField(
                choices=[
                    ("baixa", "Baixa"),
                    ("media", "Média"),
                    ("alta", "Alta"),
                    ("urgente", "Urgente"),
                ],
                default="media",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="tarefamodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("backlog", "Backlog"),
                    ("a_fazer", "A Fazer"),
                    ("em_progresso", "Em Progresso"),
                    ("concluido", "Concluído"),
                ],
                default="a_fazer",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="tarefamodel",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tarefas",
                to="tarefas.categoria",
            ),
        ),
    ]
